/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Inventory1;
import DbConn.dbconnect;
import DbConn.dbconnect;
import Inventory1.Orders;
//import dbConnect.dbcon;
import static DbConn.dbconnect.connect;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**

/**
 *
 * @author Dharshika
 */
public class Checkbills extends javax.swing.JFrame {
 String procode;
    String fabcode;
     Connection con = null;
    PreparedStatement pst = null;
    PreparedStatement pst1 = null;
    ResultSet rs = null;
    ResultSet rs1 = null;
    /**
     * Creates new form Checkbills
     */
    public Checkbills() {
    initComponents();
    Connection con = null;
    PreparedStatement pst = null;
    PreparedStatement pst1 = null;
    ResultSet rs = null;
    ResultSet rs1 = null;
    }
    public Checkbills(String y,String z)
{
    
        initComponents();
         con= dbconnect.connect();
        
      
     
     try {
         
         
         procode=y;
        fabcode=z;
       
        
        
                
        
     lbl_procode.setText(procode);
     lbl_fabcode.setText(fabcode);
          
        
           
            
            Connection connection = connect();	
            Statement st = connection.createStatement();
          //Statement st1 = connection.createStatement();
            ResultSet rs ;
           
              int fabriccode =Integer.parseInt(lbl_fabcode.getText());
            
             rs = st.executeQuery("select * from billofmaterials where procode='"+lbl_procode.getText()+"' AND fabcode='"+fabriccode+"'" );
            // ResultSet rs1;
                        //  rs1 = st1.executeQuery("select * from rawmaterials where code='"+fabriccode+"'" );
  
             
                        String procategory = "";
                         String prosubcategory = "";
                          String size = "";
                           String color = "";
                            String fabname = "";
                             String fabcolor = "";
                             String unitproduct="";
                           // String av="";
                            while(rs.next()){

                                                
                                              
                                                procategory = rs.getString("procategory");
                                                   prosubcategory = rs.getString("prosubcategory");
                                                      size = rs.getString("size");
                                                         color = rs.getString("color");
                                                                fabname = rs.getString("fabname");
                                                              fabcolor = rs.getString("fabcolor");
                                                              unitproduct =Double.toString(rs.getDouble("unitproduct"));
                                                
                                            }
                             
//                             while(rs1.next()){
//                                 
//                                  //av =Double.toString(rs.getDouble("stockqty"));
//                                 
//                                 
//                             }
                            
                            
          
            txt_procategory.setText(procategory);
            txt_prosubcategory.setText(prosubcategory);
            txt_size.setText(size);
            txt_color.setText(color);
            txt_fabname.setText(fabname);
            txt_fabcolor.setText(fabcolor);
            txt_unitproduct.setText(unitproduct);
          // txt_availablefabric.setText(av);
                      
            
           
          
    } catch (Exception e) {
    }
     
     
        
          

}  
   
    
    
    
    
    /**
 
 
 
 
 * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbl_procode = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_size = new javax.swing.JTextField();
        txt_color = new javax.swing.JTextField();
        lbl_fabcode = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_fabcolor = new javax.swing.JTextField();
        txt_unitproduct = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_availablefabric = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_made = new javax.swing.JTextField();
        txt_fabname = new javax.swing.JTextField();
        txt_procategory = new javax.swing.JTextField();
        txt_prosubcategory = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(230, 120));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(1130, 610));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Check Bill of Materials", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        lbl_procode.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_procode.setForeground(new java.awt.Color(255, 255, 255));
        lbl_procode.setText("Product code");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Product Category");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Subcategory");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Size");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Color");

        txt_size.setBackground(new java.awt.Color(204, 204, 204));
        txt_size.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txt_color.setBackground(new java.awt.Color(204, 204, 204));
        txt_color.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lbl_fabcode.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_fabcode.setForeground(new java.awt.Color(255, 255, 255));
        lbl_fabcode.setText("Fabric Code");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Fabric Name");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Fabric Color");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Units/Product");

        txt_fabcolor.setBackground(new java.awt.Color(204, 204, 204));
        txt_fabcolor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txt_unitproduct.setBackground(new java.awt.Color(204, 204, 204));
        txt_unitproduct.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_unitproduct.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_unitproductKeyReleased(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Available Fabric");

        txt_availablefabric.setBackground(new java.awt.Color(204, 204, 204));
        txt_availablefabric.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_availablefabric.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_availablefabricMouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Products can be made");

        txt_made.setBackground(new java.awt.Color(204, 204, 204));
        txt_made.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_made.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_madeMouseClicked(evt);
            }
        });
        txt_made.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_madeKeyPressed(evt);
            }
        });

        txt_fabname.setBackground(new java.awt.Color(204, 204, 204));
        txt_fabname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txt_procategory.setBackground(new java.awt.Color(204, 204, 204));
        txt_procategory.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txt_prosubcategory.setBackground(new java.awt.Color(204, 204, 204));
        txt_prosubcategory.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Meter");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_procode)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_size, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                    .addComponent(txt_color)
                    .addComponent(txt_procategory, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                    .addComponent(txt_prosubcategory, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE))
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel8)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(lbl_fabcode)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_fabcolor)
                    .addComponent(txt_made, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_availablefabric)
                    .addComponent(txt_unitproduct)
                    .addComponent(txt_fabname))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(210, 210, 210))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_procode)
                    .addComponent(lbl_fabcode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_procategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txt_prosubcategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txt_fabname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txt_fabcolor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txt_unitproduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txt_color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(txt_availablefabric, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txt_made, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(297, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1143, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_unitproductKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_unitproductKeyReleased
        
        
                                     
    
    }//GEN-LAST:event_txt_unitproductKeyReleased

    private void txt_availablefabricMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_availablefabricMouseClicked
       con= dbconnect.connect();
        String fabcode =lbl_fabcode.getText();
        
        Integer code =Integer.parseInt(fabcode);
        
        try {
            
            
            
             Connection connection = connect();	
            Statement st = connection.createStatement();
          
            ResultSet rs ;
           
             
            
            
                         rs = st.executeQuery("select * from rawmaterials where code='"+code+"'" );
  
             
                            String av="";
                            while(rs.next()){

                                                
                                             
                                                              av =Double.toString(rs.getDouble("stockqty"));
                                                
                                            }
                             
                             
                            
                            
          
           
          txt_availablefabric.setText(av);
                      
            
           
          
    } catch (Exception e) {
    }
     
            
       
        
        
        
        
        
        
    }//GEN-LAST:event_txt_availablefabricMouseClicked

    private void txt_madeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_madeKeyPressed
//        Double available= Double.parseDouble(txt_availablefabric.getText());
//        Double unitproduct = Double.parseDouble(txt_unitproduct.getText());
////        try{
//                Double made = available+unitproduct;
//                String due = Double.toString(made);
//                txt_made.setText(due);
//                            
//                    }catch(Exception ex){
//                    }
    }//GEN-LAST:event_txt_madeKeyPressed

    private void txt_madeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_madeMouseClicked
         Double available= Double.parseDouble(txt_availablefabric.getText());
        Double unitproduct = Double.parseDouble(txt_unitproduct.getText());
//        try{
                Double made = available/unitproduct;
                Integer i = made.intValue();
                String due = Integer.toString(i);
                txt_made.setText(due);
    }//GEN-LAST:event_txt_madeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Checkbills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Checkbills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Checkbills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Checkbills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Checkbills().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_fabcode;
    private javax.swing.JLabel lbl_procode;
    private javax.swing.JTextField txt_availablefabric;
    private javax.swing.JTextField txt_color;
    private javax.swing.JTextField txt_fabcolor;
    private javax.swing.JTextField txt_fabname;
    private javax.swing.JTextField txt_made;
    private javax.swing.JTextField txt_procategory;
    private javax.swing.JTextField txt_prosubcategory;
    private javax.swing.JTextField txt_size;
    private javax.swing.JTextField txt_unitproduct;
    // End of variables declaration//GEN-END:variables
}
