/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Inventory1;
import Inventory1.Purchases;
import DbConn.dbconnect;
import static DbConn.dbconnect.connect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Dharshika
 */
public class SupplierPayments extends javax.swing.JFrame {

       
    String suppid;
    String suppname;
    String totalcoast;
    Connection con = null;
    PreparedStatement pst = null;
    PreparedStatement pst1 = null;
    ResultSet rs = null;
    ResultSet rs1 = null;
    
    
    public SupplierPayments() {
    con= dbconnect.connect();
    Connection con = null;
    PreparedStatement pst = null;
    PreparedStatement pst1 = null;
    ResultSet rs = null;
    ResultSet rs1 = null;
    initComponents();
         
         showjTable();
    }
    
    
    
    public SupplierPayments(String y,String z,String xx) {
       
        initComponents();
         con= dbconnect.connect();
         try {         
        suppid =y;
        suppname=z;
        totalcoast=xx;
        
        
                
        
        txt_paysuppid.setText(suppid);
        txt_paybusinessname.setText(suppname);
        txt_paytotalamount.setText(totalcoast);
        
          
            
            Connection connection = connect();	
            Statement st = connection.createStatement();
            ResultSet rs ;
             rs = st.executeQuery("select * from supplierpurchases where purchaseorderno= (select MAX(purchaseorderno) from supplierpurchases)");
             
                        String purchaseorderno = "";
            
                           

                            while(rs.next()){

                                                
                                              
                                                purchaseorderno = rs.getString("purchaseorderno");
                                                
                                            }
           
            txt_paypurchaseno.setText(purchaseorderno);
                     
            
            
            
        }
        catch (Exception e) {
        }
        
    }

  
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_paypurchaseno = new javax.swing.JTextField();
        txt_paysuppid = new javax.swing.JTextField();
        txt_paybusinessname = new javax.swing.JTextField();
        cmb_paymenttype = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_paypaidamount = new javax.swing.JTextField();
        txt_paydueamount = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_paytotalamount = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btn_insert = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lbl_payid = new javax.swing.JLabel();
        date_paymentdate = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_payment = new javax.swing.JTable();

        jButton4.setText("jButton4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(230, 120));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(1130, 610));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Payment Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(51, 51, 51));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Supplier ID");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Supplier Business Name");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Payment Type");

        txt_paypurchaseno.setBackground(new java.awt.Color(153, 153, 153));
        txt_paypurchaseno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txt_paysuppid.setBackground(new java.awt.Color(153, 153, 153));
        txt_paysuppid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txt_paybusinessname.setBackground(new java.awt.Color(153, 153, 153));
        txt_paybusinessname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        cmb_paymenttype.setBackground(new java.awt.Color(153, 153, 153));
        cmb_paymenttype.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmb_paymenttype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Cash", "Cheque", "Deposit" }));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Paid Amount");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Due Amount");

        txt_paypaidamount.setBackground(new java.awt.Color(153, 153, 153));
        txt_paypaidamount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_paypaidamount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_paypaidamountKeyReleased(evt);
            }
        });

        txt_paydueamount.setBackground(new java.awt.Color(153, 153, 153));
        txt_paydueamount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Order No");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Payment Date");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Total amount");

        txt_paytotalamount.setBackground(new java.awt.Color(153, 153, 153));
        txt_paytotalamount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));

        btn_insert.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_insert.setText("Add");
        btn_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insertActionPerformed(evt);
            }
        });

        btn_delete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_update.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Payment ID");

        lbl_payid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_payid.setForeground(new java.awt.Color(255, 255, 255));
        lbl_payid.setText("ID");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9)
                    .addComponent(jLabel4)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel1))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_payid)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(date_paymentdate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_paybusinessname, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_paysuppid, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_paypurchaseno, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmb_paymenttype, 0, 204, Short.MAX_VALUE)
                            .addComponent(txt_paypaidamount, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_paydueamount, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_paytotalamount))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel11))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addComponent(btn_insert, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbl_payid))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_paypurchaseno, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_paysuppid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txt_paybusinessname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmb_paymenttype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(date_paymentdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_paytotalamount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_paypaidamount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_paydueamount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(btn_insert)
                    .addComponent(btn_delete)
                    .addComponent(btn_update))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        tbl_payment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Payment ID", "Order No", "Supplier ID", "Supplier Business  Name", "Payment Type", "Payment Date", "Total amount", "Paid amount", "Due Amount"
            }
        ));
        tbl_payment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_paymentMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_payment);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1142, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_paypaidamountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_paypaidamountKeyReleased
        Double totalcost = Double.parseDouble(txt_paytotalamount.getText());
        Double paidamount = Double.parseDouble(txt_paypaidamount.getText());
        try{
                Double dueamount=totalcost-paidamount;
                String due = String.valueOf(dueamount);
                txt_paydueamount.setText(due);
                            
                    }catch(Exception ex){
                                        }
        
    }//GEN-LAST:event_txt_paypaidamountKeyReleased
    
     public ArrayList<Supplierpaymentsemodel> getSupplierPaymentsList()
    {
        ArrayList<Supplierpaymentsemodel> supplierPaymentsList=new ArrayList<>();
        Connection connection = connect();
        String query="Select * from supplierpayments";
        
        Statement st;
        ResultSet rs;
        
        try {
            st=connection.createStatement();
            rs=st.executeQuery(query);
            Supplierpaymentsemodel paymentmodel;
            
            while(rs.next())
            {
             paymentmodel=new Supplierpaymentsemodel(rs.getInt("paymentid"),rs.getInt("purchaseorderno"), rs.getInt("supplierid"),                 
                        rs.getString("businessname"), rs.getString("paymenttype"), rs.getDate("paymentdate"), 
                        rs.getDouble("totalamount"), rs.getDouble("paidamount"), rs.getDouble("dueamount"));
                
                        supplierPaymentsList.add(paymentmodel);
            }
                    
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        return supplierPaymentsList;
    }
      public void showjTable()
    {
        ArrayList<Supplierpaymentsemodel> listdata=getSupplierPaymentsList();
        DefaultTableModel model =(DefaultTableModel)tbl_payment.getModel();
        
        Object [] row=new Object[9];
        for(int i = 0;i<listdata.size();i++)
        {
            row[0]=listdata.get(i).getPaymentid();
            row[1]=listdata.get(i).getPurchaseorderno();
            row[2]=listdata.get(i).getSupplierid();
            row[3]=listdata.get(i).getBusinessname();
            row[4]=listdata.get(i).getPaymenttype();
            row[5]=listdata.get(i).getPaymentdate();
            row[6]=listdata.get(i).getTotalamount();
            row[7]=listdata.get(i).getDueamount();
            row[8]=listdata.get(i).getPaidamount();
            
            
            model.addRow(row);
        }
    
    }
   
    
    
    
    private void btn_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insertActionPerformed
         
         SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
         
         
         String query="INSERT INTO `supplierpayments`(`purchaseorderno`,`supplierid`,`businessname`,`paymenttype`,`paymentdate`,`totalamount`,`paidamount`,`dueamount`)VALUES ('"+txt_paypurchaseno.getText()+"','"+txt_paysuppid.getText()+"','"+txt_paybusinessname.getText()+"','"+cmb_paymenttype.getSelectedItem()+"','"+dateFormat.format(date_paymentdate.getDate()) +"','"+txt_paytotalamount.getText()+"','"+txt_paypaidamount.getText()+"','"+txt_paydueamount.getText()+"')";
       
         executeSqlQuery(query, "Insert");
                    

                    
    }//GEN-LAST:event_btn_insertActionPerformed

    private void tbl_paymentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_paymentMouseClicked
        
        
        int i=tbl_payment.getSelectedRow();
        TableModel model=tbl_payment.getModel();
        
       
        try { 
            
        lbl_payid.setText(model.getValueAt(i, 0).toString());
        txt_paypurchaseno.setText(model.getValueAt(i, 1).toString());
        txt_paysuppid.setText(model.getValueAt(i, 2).toString());
        txt_paybusinessname.setText(model.getValueAt(i, 3).toString());
        cmb_paymenttype.setSelectedItem(model.getValueAt(i, 4).toString());
        date_paymentdate.setDate(new SimpleDateFormat("yyyy-MM-dd").parse(model.getValueAt(i,5).toString()));
        txt_paytotalamount.setText(model.getValueAt(i, 6).toString());
        txt_paypaidamount.setText(model.getValueAt(i, 7).toString());
        txt_paydueamount.setText(model.getValueAt(i, 8).toString());
            
        } catch (Exception e) {
        }
       
        
        
        
        
      
       
    }//GEN-LAST:event_tbl_paymentMouseClicked

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
      String query="DELETE FROM `supplierpayments` WHERE `paymentid`='"+lbl_payid.getText()+"'";
       executeSqlQuery(query, "Delete");
        
                           
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        int x = JOptionPane.showConfirmDialog(null,"Do you want to Update record?");
        
        if(x==0)
        {
        
        String query="UPDATE `supplierpayments` SET `paymenttype`='"+cmb_paymenttype.getSelectedItem()+"',`totalamount`='"+txt_paytotalamount.getText()+"',`paidamount`='"+txt_paydueamount.getText()+"',`dueamount`='"+txt_paydueamount.getText()+"'WHERE `paymentid`='"+lbl_payid.getText()+"'";
        executeSqlQuery(query, "Update");
        
        
        
         }
        else if( x==1) {
                  
                  ClearField();
              }
        
        
    }//GEN-LAST:event_btn_updateActionPerformed
 
     public void executeSqlQuery(String query,String message)
     {
         Connection conn= connect();
         Statement st;
         try {
              st=con.createStatement();
              if((st.executeUpdate(query))==1)
              {
                  // data get refresh after query runs 
                  DefaultTableModel model = (DefaultTableModel)tbl_payment.getModel();
                  model.setRowCount(0);
                  showjTable();
                                    
                  // message box
                  JOptionPane.showMessageDialog(null, "Data "+message+" Successfully");
                  ClearField();
              }else{
                  JOptionPane.showMessageDialog(null, "Data "+message+" Failed");
              }
         } catch (Exception e) {
             JOptionPane.showMessageDialog(null, e);
            
         }
         
     }
    
    
    
    public void ClearField()
    {
        
        txt_paybusinessname.setText(null);
        cmb_paymenttype.setSelectedItem(null);
        txt_paydueamount.setText(null);
        txt_paypaidamount.setText(null);
        txt_paypurchaseno.setText(null);
        txt_paysuppid.setText(null);
        txt_paytotalamount.setText(null);
       date_paymentdate.setDate(null); 
   }
    
    
    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SupplierPayments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SupplierPayments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SupplierPayments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SupplierPayments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SupplierPayments().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_insert;
    private javax.swing.JButton btn_update;
    private javax.swing.JComboBox cmb_paymenttype;
    private com.toedter.calendar.JDateChooser date_paymentdate;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_payid;
    private javax.swing.JTable tbl_payment;
    private javax.swing.JTextField txt_paybusinessname;
    private javax.swing.JTextField txt_paydueamount;
    private javax.swing.JTextField txt_paypaidamount;
    private javax.swing.JTextField txt_paypurchaseno;
    private javax.swing.JTextField txt_paysuppid;
    private javax.swing.JTextField txt_paytotalamount;
    // End of variables declaration//GEN-END:variables
}
