/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package security_managment;

import DbConn.dbconnect;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;



/**
 *
 * @author Tharindu sachintha
 */
public class Vehicle extends javax.swing.JFrame {

    
    Connection con=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    
    /**
     * Creates new form Income_Vehicle
     */
    public Vehicle() {
        initComponents();
        con=dbconnect.connect();
        SetTable();
        //place.setEditable(false);
        //no.setEditable(false);
        
    }
    
    void SetTable()
    {
            String sql="select pid,did,date,model,vno,parkp,parkno,Leve from vehicle";
            
            try{
                pst=con.prepareStatement(sql);
                rs=pst.executeQuery();
                
                table.setModel(DbUtils.resultSetToTableModel(rs));
                
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,e);
            }
    }
    void reset()
    {
                vno.setText(null);
                did.setText(null);
                dn.setText(null);
                pid.setText(null);
                place.setText(null);
                mcombo.setSelectedIndex(0);
                no.setText(null);
                dte.setDate(null);
                se.setText(null);
    
        
    
    
    
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        vno = new javax.swing.JTextField();
        did = new javax.swing.JTextField();
        place = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        se = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        pid = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        no = new javax.swing.JTextField();
        mcombo = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        dn = new javax.swing.JTextField();
        lable = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        jLabel11.setText("Search");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(165, 130));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1180, 620));
        setSize(new java.awt.Dimension(1160, 680));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Vehicle Number");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 75, 110, -1));

        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Vehicle Model");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, -1, -1));

        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Park Place and Number");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 80, -1, -1));
        jPanel1.add(vno, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 100, -1));
        jPanel1.add(did, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 100, -1));
        jPanel1.add(place, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 70, 70, 30));

        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("Date of Time");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 110, -1));
        jPanel1.add(se, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 180, 30));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 0, 0));
        jLabel21.setText("Vehicle Details");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 210, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, -1));

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel4MouseExited(evt);
            }
        });

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Delete");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 100, 40));

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel5MouseExited(evt);
            }
        });

        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Search");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 160, 90, 30));

        jPanel6.setBackground(new java.awt.Color(102, 102, 102));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel6MouseExited(evt);
            }
        });

        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Update");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel24)
                .addGap(19, 19, 19))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 98, 40));

        jPanel7.setBackground(new java.awt.Color(102, 102, 102));
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel7MouseExited(evt);
            }
        });

        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Add");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 100, 40));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "PID", "Driver ID", "Date", "Model", "Vehicle No", "Park Place ", "Park No", "Leave"
            }
        ));
        jScrollPane1.setViewportView(table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 760, 310));

        pid.setForeground(new java.awt.Color(240, 240, 240));
        pid.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));
        jPanel1.add(pid, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 120, 90, 20));

        jLabel19.setForeground(new java.awt.Color(240, 240, 240));
        jLabel19.setText("Driver Id");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 90, -1));

        no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noActionPerformed(evt);
            }
        });
        jPanel1.add(no, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 70, 70, 30));

        mcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select model", "Car and Van", "Lorry", "Bike" }));
        mcombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                mcomboItemStateChanged(evt);
            }
        });
        mcombo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mcomboKeyReleased(evt);
            }
        });
        jPanel1.add(mcombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, -1, -1));

        jLabel12.setForeground(new java.awt.Color(240, 240, 240));
        jLabel12.setText("Driver name");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 110, -1));
        jPanel1.add(dn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 100, -1));

        lable.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(lable, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 80, 70, 30));

        jPanel8.setBackground(new java.awt.Color(102, 102, 102));
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel8MouseExited(evt);
            }
        });

        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("leave");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 160, -1, 30));

        jLabel13.setForeground(new java.awt.Color(240, 240, 240));
        jLabel13.setText("Park Id");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 60, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1415, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseClicked
        // TODO add your handling code here:
      SimpleDateFormat sd = new SimpleDateFormat("yyyy,MM,dd, HH:mm:ss");
        
        String vehino=vno.getText();
        String driverid=did.getText();
        String drname=dn.getText();
        String modell = mcombo.getSelectedItem().toString();
        String datee ;//= sd.format(dte.getDate());
        String pkno=no.getText();
        String pkp=place.getText();
        
        Calendar cal = Calendar.getInstance();
        datee=(sd.format(cal.getTime()));

        try{
            String sql="INSERT INTO vehicle(vno,did,dname,model,parkno,parkp,date)"
                    +"VALUES('"+vehino+"','"+driverid+"','"+drname+"','"+modell+"','"+pkno+"','"+pkp+"','"+datee+"')";
            
            String sq="INSERT INTO leavevehicle(model) VALUES('"+modell+"')";
        
            String model=(String)mcombo.getSelectedItem();
            
            pst=con.prepareStatement(sql);
            pst=con.prepareStatement(sq);
          
            if(model.equals("Car and Van"))
            {
                place.setText("A Park");
            }
            else if(model.equals("Lorry"))
            {
                place.setText("B Park");
            }
            else if(model.equals("Bike"))
            {
                place.setText("Park C");
            }
            
            pst.execute(sql);
            pst.execute(sq);
            JOptionPane.showMessageDialog(null,"success");
            SetTable();
            reset();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jPanel7MouseClicked

    private void mcomboKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mcomboKeyReleased
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_mcomboKeyReleased

    private void mcomboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_mcomboItemStateChanged
        // TODO add your handling code here:
        String sql="select count(model) from leavevehicle where model=?";
            String modl=(String)mcombo.getSelectedItem();
        try{
            pst=con.prepareStatement(sql);
            
            pst.setString(1,modl);
            rs=pst.executeQuery();
          
            int count = -1;

            while(rs.next())
            {
                count = rs.getInt(1);
                
            }
                
                if(modl.equals("Car and Van") && count<=5 )
                {
                    place.setText("A Park");
                    no.setText(String.valueOf(++count));
                    lable.setText(null);
            
                 }
                else if(modl.equals("Lorry") && count<=10)
                {
                    place.setText("B Park");
                    no.setText(String.valueOf(++count));
                    lable.setText(null);
                }
                else if(modl.equals("Bike") && count<=10)
                {
                    place.setText("Park C");
                    no.setText(String.valueOf(++count));
                    lable.setText(null);
                }
                else if(modl.equals("Select model"))
                {
                    place.setText(null);
                    no.setText(null);
                    lable.setText(null);
                }
                else
                {
                    place.setText(null);
                    no.setText(null);
                    lable.setText("full");
                }
            
        }    
        catch(Exception e)
        {
        
        }
        
    }//GEN-LAST:event_mcomboItemStateChanged

    private void jPanel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseEntered
        // TODO add your handling code here:
        jPanel7.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_jPanel7MouseEntered

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        // TODO add your handling code here:
           
        String sql="select * from vehicle where pid=?";
        
        try{
            
            pst=con.prepareStatement(sql);
            pst.setString(1,se.getText());
            rs=pst.executeQuery();
            
            if(rs.next())
            {
                vno.setText(rs.getString("vno"));
                did.setText(rs.getString("did"));
                dn.setText(rs.getString("dname"));
                pid.setText(rs.getString("pid"));
                place.setText(rs.getString("parkp"));
                mcombo.setSelectedItem(rs.getString("model"));
               // dte.set
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Invalid Park Id");
                reset();
            }
        }
        catch(Exception e)
        {
        
        }
        
        
        
    }//GEN-LAST:event_jPanel5MouseClicked

    private void jPanel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseClicked
        // TODO add your handling code here:
        String sql="delete from leavevehicle where pid=?";
        String s="update vehicle set  Leve='leave' where pid=?";
       
        
        try{
            pst=con.prepareStatement(sql);
            pst.setString(1,se.getText());
            
            int msg=JOptionPane.showConfirmDialog(null,"is it leave :"+se.getText(), "close",JOptionPane.YES_OPTION,JOptionPane.NO_OPTION);
            
            if(msg==JOptionPane.YES_OPTION)
            {
                pst.executeUpdate();
                pst=con.prepareStatement(s);
                pst.setString(1,se.getText());
                pst.executeUpdate();
            }
           
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
        reset();
        SetTable();
    }//GEN-LAST:event_jPanel8MouseClicked

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        // TODO add your handling code here:
        int x=JOptionPane.showConfirmDialog(null,"Do you really want to update");
        if (x==0);
            String sql="update vehicle set  did=?,dname=?,model=?,vno=?,parkp=?,parkno=? where pid=?";
        
        try{
            pst=con.prepareStatement(sql);
            
           pst.setString(1,did.getText());
           pst.setString(2,dn.getText());
           pst.setString(3, (String)mcombo.getSelectedItem());
           pst.setString(4,vno.getText());
           pst.setString(5,place.getText());
           pst.setString(6,no.getText());
           pst.setString(7,se.getText());       
            
            pst.executeUpdate();
            
            
            JOptionPane.showMessageDialog(null,"Susess");
           
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
         SetTable();
         reset();
    }//GEN-LAST:event_jPanel6MouseClicked

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        // TODO add your handling code here:
        
             String sql="delete from vehicle where pid=? ";
             
              String sq="delete from leavevehicle where pid=?";            
        
        String id=pid.getText();
        
        try{
            pst=con.prepareStatement(sql);
            pst.setString(1,pid.getText());
            
            int msg=JOptionPane.showConfirmDialog(null,"Do you need to delete vehicle details :"+id, "close",JOptionPane.YES_OPTION,JOptionPane.NO_OPTION);
            
            if(msg==JOptionPane.YES_OPTION)
            {
                pst.executeUpdate();
                
                pst=con.prepareStatement(sq);
                pst.setString(1,se.getText());
                pst.executeUpdate();
            }
            
            
        }
        catch(Exception e)
        {
        
        }
        reset();
        SetTable();
        
    }//GEN-LAST:event_jPanel4MouseClicked

    private void noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noActionPerformed

    private void jPanel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseEntered
        // TODO add your handling code here:
           jPanel6.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_jPanel6MouseEntered

    private void jPanel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseEntered
        // TODO add your handling code here:
                jPanel4.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_jPanel4MouseEntered

    private void jPanel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseEntered
        // TODO add your handling code here:
                jPanel5.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_jPanel5MouseEntered

    private void jPanel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseEntered
        // TODO add your handling code here:
                jPanel8.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_jPanel8MouseEntered

    private void jPanel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseExited
        // TODO add your handling code here:
         jPanel7.setBackground(new Color(102,102,102));
    }//GEN-LAST:event_jPanel7MouseExited

    private void jPanel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseExited
        // TODO add your handling code here:
         jPanel6.setBackground(new Color(102,102,102));
    }//GEN-LAST:event_jPanel6MouseExited

    private void jPanel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseExited
        // TODO add your handling code here:
         jPanel4.setBackground(new Color(102,102,102));
    }//GEN-LAST:event_jPanel4MouseExited

    private void jPanel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseExited
        // TODO add your handling code here:
         jPanel5.setBackground(new Color(102,102,102));
    }//GEN-LAST:event_jPanel5MouseExited

    private void jPanel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseExited
        // TODO add your handling code here:
         jPanel8.setBackground(new Color(102,102,102));
    }//GEN-LAST:event_jPanel8MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vehicle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField did;
    private javax.swing.JTextField dn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lable;
    private javax.swing.JComboBox<String> mcombo;
    private javax.swing.JTextField no;
    private javax.swing.JLabel pid;
    private javax.swing.JTextField place;
    private javax.swing.JTextField se;
    private javax.swing.JTable table;
    private javax.swing.JTextField vno;
    // End of variables declaration//GEN-END:variables
}
